<?php 
//Labels
define('LABEL_USER_EMAIL'				, 'E-mail');
define('LABEL_USER_NAME'				, 'Nome/Razão social');
define('LABEL_USER_DOCUMENT'			, 'CPF/CNPJ');
define('LABEL_USER_ADDRESS_LINE_A'		, 'Logradouro');
define('LABEL_USER_ADDRESS_LINE_B'		, 'Complemento');
define('LABEL_USER_DISTRICT'			, 'Bairro');
define('LABEL_USER_CITY'				, 'Cidade');
define('LABEL_USER_STATE'				, 'Estado');
define('LABEL_USER_COUNTRY'				, 'País');
define('LABEL_USER_ZIP'					, 'CEP');
define('LABEL_USER_PHONE'				, 'Telefone');
define('LABEL_USER_CELLPHONE'			, 'Celular');

//Index
define('LABEL_PERSONAL_DATA'			, 'Dados pessoais');
define('LABEL_CHANGE_PASSWORD'			, 'Alteração de senha');
define('LABEL_ADDRESS'					, 'Endereço');

define('BTN_CHANGE_PASSWORD' 			, 'Alterar senha');

//Title
define('TITLE_ACCOUNT_CHANGE_DATA'		, 'Alteração de dados');