<?php
//HOME
define('TITLE_INDEX'				, 'Algum erro misterioso acabou de acontecer');
define('TITLE_HTTP400'				, 'Bad Request');
define('TITLE_HTTP401'				, 'Sem autorização');
define('TITLE_HTTP403'				, 'Acesso proibido');
define('TITLE_HTTP404'				, 'Página não encontrada');
define('TITLE_HTTP500'				, 'Erro interno do servidor');
define('TITLE_SIGNUP_CONFIRMATION'	, 'Erro na confirmação de cadastro');

//SignUp
define('LABEL_ERR_SIGNUP'			, '<p>Houve um erro na confirmação de seu registro ou o código de confirmação já foi validado.</p>
										<p>Se o erro persistir por favor contate-nos.</p>');

//RecoverSent
define('LABEL_ERR_RECOVER'			, '<p>Houve um erro na requisição de sua senha.</p>
										<p>Se o erro persistir por favor contate-nos.</p>');
define('TITLE_EMAIL_CONFIRMATION'	, 'Erro na confirmação de email');
