<?php
//LOGIN
define('TITLE_INDEX'					, 'Login');
define('TITLE_RECOVER'					, 'Recuperação de senha');
define('TITLE_CONFIRMED'				, 'Confirmação de senha');

//Messages
define('MESSAGE_EMAIL_DONT_EXIST'		, 'O e-mail informado não foi encontrado. Por favor verifique se o e-mail está digitado correto e tente novamente.');
define('MESSAGE_LOGIN_FAIL'				, '<p>Falha ao realizar login. Por favor verifique se o usuário e senha foram digitados corretamente.</p>');

//Recover
define('SUBJECT_EMAIL_RECOVER'			, 'Shopitos - Recuperação de senha');
define('DISCLAIMER_RECOVER_INDEX'		, 'Nesta página você poderá recuperar uma senha esquecida. Por favor digite seu e-mail de cadastro e clique em <em>Enviar</em>.');
define('DISCLAIMER_RECOVER_SENT'		, 'Uma mensagem foi enviada para seu e-mail de cadastro contendo instruções para recuperação da senha.');
define('DISCLAIMER_RECOVER_CONFIRM'		, '<p>Por favor digite sua nova senha e sua confirmação ao lado.</p>
											<p>Após a troca de senha, você será automaticamente autenticado no <strong class="highlight-text-medium">Portal Shopitos</strong>.');