<?php
define('TITLE_INDEX'					, 'Registro');
define('TITLE_TERMS'					, 'Termos e condições de uso');
define('TITLE_SUCCESS'					, 'Registro concluído');
define('TITLE_CONFIRMED'				, 'Registro confirmado');

//Labels
define('LABEL_USER_EMAIL'				, 'E-mail');
define('LABEL_USER_NAME'				, 'Nome/Razão social');
define('LABEL_USER_DOCUMENT'			, 'CPF/CNPJ');
define('LABEL_USER_ADDRESS_LINE_A'		, 'Logradouro');
define('LABEL_USER_ADDRESS_LINE_B'		, 'Complemento');
define('LABEL_USER_DISTRICT'			, 'Bairro');
define('LABEL_USER_CITY'				, 'Cidade');
define('LABEL_USER_STATE'				, 'Estado');
define('LABEL_USER_COUNTRY'				, 'País');
define('LABEL_USER_ZIP'					, 'CEP');
define('LABEL_USER_PHONE'				, 'Telefone');
define('LABEL_USER_CELLPHONE'			, 'Celular');

//Messages
define('MESSAGE_USER_EXISTS'			, 'O e-mail informado já existe na nossa base de dados. Você tem certeza de que não é um usuário cadastrado?');
define('MESSAGE_DOCUMENT_EXISTS'		, 'Hum... Já há um usuário cadastrado com este documento. Se for você mesmo e não lembrar sua senha, <a href="%s">clique aqui</a> para acessar a página de recuperação de senha.');
define('MESSAGE_CONFIRMATION_ERROR'		, 'A senha e sua confirmação devem ser iguais.');

//E-mail
define('SUBJECT_EMAIL_SIGNUP'			, 'Shopitos - Registro de usuário');

//Buttons
define('BTN_TERMS_ACCEPT'				, 'Aceito os termos');
define('BTN_TERMS_NOT_ACCEPT'			, 'Não aceito os termos');

//Success
define('LABEL_SUCCESS'					, '<p>Conta criada com sucesso!</p>
											<p>Assim que possível, por favor acesse seu e-mail e clique no link para confirmar seu cadastro.</p>
											<p>Enquanto isso, você já pode começar a desfrutar do maravilhoso mundo dos <strong class="highlight-text-large">Shopitos!</strong>.</p>
											<p>Por favor aguarde enquanto autenticamos seu acesso.</p>');

//Index
define('LABEL_DATA_ACCESS'				, 'Dados de acesso');
define('LABEL_PERSONAL_DATA'			, 'Dados pessoais');
define('LABEL_ADDRESS'					, 'Endereço');
define('INDEX_DISCLAIMER'				, '<h3>Só com Shopitos você tem tantas vantagens!</h3>
						             		<p>
						             			Imagine ter a sua loja virtual <strong class="highlight-text-medium">sem limite de cadastro de produtos</strong> 
												e <strong class="highlight-text-medium">sem banners</strong>  publicitários invasivos. Uma loja adaptada para funcionar 
												em <strong class="highlight-text-medium">qualquer mídia</strong>, do mobile ao tablet, da internet à TV digital. Uma loja 
												com <strong class="highlight-text-medium">controle de estoque, cálculo de frete, relatórios de 
												acesos e vendas</strong> e integrada aos mesmos <strong class="highlight-text-medium">meios de pagamento</strong>
												usados pelos maiores portais de e-commerce do mundo. Imagine sua loja com 
												<strong class="highlight-text-medium">webmail corporativo</strong> e integrada às <strong class="highlight-text-medium">redes sociais</strong>. Uma loja
												facilmente <strong class="highlight-text-medium">customizável</strong>, com sistema de atualização simplificado e feita
												sob medida para expor e <strong class="highlight-text-medium">vender os seus produtos</strong>. Imagine tudo isso
												<strong class="highlight-text-medium">grátis</strong> e ainda podendo usar o seu <strong class="highlight-text-medium">próprio domínio</strong>.
						             		</p>
						             		<p>
												Agora <strong class="highlight-text-medium">pare de imaginar</strong> e venha criar sua loja virtual com a gente.
												Torne-se hoje mesmo um <strong class="highlight-text-medium">Shopito</strong> e comece a vender os seus produtos!
						             		</p>');

//Terms
define('DISCLAIMER_TERMS'					, '<p><strong class="highlight-text-normal">Você deve aceitar os termos de uso antes de continuar. Role a página para aceitá-los.</strong></p>');

//Confirmed
define('LABEL_CONFIRMED'				, '<p><strong class="highlight-text-large">Conta confirmada com sucesso!</strong></p>
											<p>Por favor aguarde enquanto autenticamos seu acesso.</p>');